config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datacollections/models.py
from django.db import models
from products import models as products_models
from products.models import Product as product
from products_users.models import Products_User as pu

# Create your models here.
class Datacollection(models.Model):
    """How Data looks like"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    image = models.ImageField(upload_to="data_photos", blank=True)
    data_gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    data_age = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = models.ForeignKey(
        "products.Product",
        related_name="datacollections",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

detection/models/classify.py
# -*- coding:utf -*-
import torch.nn as nn
import torch.nn.functional as f


class SexClassify(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.classify = nn.Sequential(
            nn.Linear(input_size, 1000),
            nn.BatchNorm1d(1000),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.5),
            nn.Linear(1000, 1000),
            nn.BatchNorm1d(1000),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.5),
            nn.Linear(1000, 2)
        )

    def forward(self, inputs):
        x = self.classify(inputs)
        return x


class AgeClassify(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.classify = nn.Sequential(
            nn.Linear(input_size, 1000),
            nn.BatchNorm1d(1000),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.5),
            nn.Linear(1000, 1000),
            nn.BatchNorm1d(1000),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.5),
            nn.Linear(1000, 10)
        )

    def forward(self, inputs):
        x = self.classify(inputs)
        return x


class Classify(nn.Module):
    def __init__(self, input_size=2048):
        super().__init__()
        self.sex_classify = SexClassify(input_size)
        self.age_classify = AgeClassify(input_size)

    def forward(self, inputs):
        sex_out = self.sex_classify(inputs)
        age_out = self.age_classify(inputs)
        return {'sex': sex_out, 'age': age_out}

detection/models/face_recognition.py
# -*- coding:utf-8 -*-
import torch
import torch.nn as nn
from detection.models.classify import Classify


class BasicCNN(nn.Module):
    def __init__(self, in_channels, output_channels, kernel_size, stride, padding=0):
        super().__init__()
        self.layer = nn.Sequential(
            nn.Conv2d(in_channels=in_channels, out_channels=output_channels,
                      kernel_size=kernel_size, stride=stride, padding=padding),
            nn.BatchNorm2d(num_features=output_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, inputs):
        x = self.layer(inputs)
        return x


class NaiveInceptionV1(nn.Module):
    def __init__(self, in_channels, _1x1, _3x3, _5x5, _pool_proj):
        super().__init__()
        self.branch1 = BasicCNN(in_channels=in_channels, output_channels=_1x1, kernel_size=(1, 1), stride=1)
        self.branch2 = BasicCNN(in_channels=in_channels, output_channels=_3x3, kernel_size=(3, 3), stride=1, padding=1)
        self.branch3 = BasicCNN(in_channels=in_channels, output_channels=_5x5, kernel_size=(5, 5), stride=1, padding=2)
        self.branch4 = nn.Sequential(
            nn.MaxPool2d(kernel_size=(3, 3), stride=1, padding=1),
            BasicCNN(in_channels=in_channels, output_channels=_pool_proj, kernel_size=(1, 1), stride=1)
        )

    def forward(self, inputs):
        x1 = self.branch1(inputs)
        x2 = self.branch2(inputs)
        x3 = self.branch3(inputs)
        x4 = self.branch4(inputs)
        x = torch.cat([x1, x2, x3, x4], dim=1)
        return x


class FRNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Stem layer
        self.stem = nn.Sequential(
            BasicCNN(in_channels=3, output_channels=32, kernel_size=(3, 3), stride=1, padding=1),
            nn.MaxPool2d(kernel_size=2, stride=2),
        )

        # InceptionV1 Convolution Layer
        self.inception = nn.Sequential(
            NaiveInceptionV1(
                in_channels=32, _1x1=32, _3x3=32, _5x5=16, _pool_proj=16
            ),
            NaiveInceptionV1(
                in_channels=96, _1x1=32, _3x3=32, _5x5=16, _pool_proj=16
            ),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        # fully connected layer
        self.fc = Classify(input_size=24576)

    def forward(self, inputs):
        x = self.stem(inputs)
        x = self.inception(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

detection/models/vgg.py
# -*- coding:utf-8 -*-
import torch.nn as nn
from detection.models.classify import Classify

cfg = {
    'vgg-s': [64,     'M', 128,      'M', 256, 256,           'M'],
    'vgg11': [64,     'M', 128,      'M', 256, 256,           'M', 512, 512,           'M', 512, 512,           'M'],
    'vgg13': [64, 64, 'M', 128, 128, 'M', 256, 256,           'M', 512, 512,           'M', 512, 512,           'M'],
    'vgg16': [64, 64, 'M', 128, 128, 'M', 256, 256, 256,      'M', 512, 512, 512,      'M', 512, 512, 512,      'M'],
    'vgg19': [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 256, 'M', 512, 512, 512, 512, 'M', 512, 512, 512, 512, 'M']
}


class VGG(nn.Module):
    def __init__(self, vgg_type, batch_norm=True):
        super().__init__()
        self.vgg_type = vgg_type
        self.batch_norm = batch_norm
        self.cnn = self.cnn_layers()
        self.classify = Classify()

    def forward(self, inputs):
        cnn_output = self.cnn(inputs)
        x = cnn_output.view(cnn_output.size(0), -1)
        x = self.classify(x)
        return x

    def cnn_layers(self):
        layers = []

        input_channel = 3
        for output_channel in cfg[self.vgg_type]:
            if output_channel == 'M':
                layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
                continue

            layers += [
                nn.Conv2d(in_channels=input_channel, out_channels=output_channel,
                          kernel_size=(3, 3), padding=1)
            ]

            if self.batch_norm:
                layers += [nn.BatchNorm2d(output_channel)]

            layers += [nn.ReLU(inplace=True)]
            input_channel = output_channel

        return nn.Sequential(*layers)


if __name__ == '__main__':
    pass

products/models.py
from django.db import models
from products_users import models as user_models

# Create your models here.
class Product(models.Model):
    """Rasberry pi model"""

    name = models.CharField(max_length=50)
    serial_number = models.CharField(max_length=50)
    user = models.ForeignKey(
        user_models.Products_User,
        related_name="products",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

products_users/models.py
from django.db import models

# Create your models here.
class Products_User(models.Model):
    user_name = models.CharField(max_length=10)

    def __str__(self):
        return self.user_name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    """Admin USER Model"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    # created = models.DateTimeField(auto_now_add=True)
    # updated = models.DateTimeField(auto_now=True)

datacollections/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render

# Create your views here.

products_users/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

datacollections/templates/change_list_graph.html
{% extends "admin/change_list.html" %} 
{% load staticfiles %} 
{% block extrahead %}
<link
  rel="stylesheet"
  type="text/css"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js"></script>
<script>
function randomColorGenerator() {
    return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
};
const timeFormat = 'HH';
const hours = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23];
var options = {
    responsive: true,
    maintainAspectRatio: true,
    legend: {
        position: 'left'
    },
    title: {
        display: true
    },
    animation: {
        animateScale: true,
        animateRotate: true
    }
};

window.onload = function () {
    let ctx = document.getElementById("gender-chart");
    {% regroup cl.queryset|dictsort:"data_gender" by get_data_gender_display as gender_list %}
    let lineChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [{% for gender in gender_list %}'{{ gender.grouper }}',{% endfor %}],
            datasets: [{
                data: [{% for gender in gender_list %}'{{ gender.list|length }}',{% endfor %}],
                backgroundColor: [{% for gender in gender_list %}randomColorGenerator(),{% endfor %}]
            }]
        },
        options: options
    });
    ctx = document.getElementById("model-chart");
    let temp=[];
    let bg=[];
    let dats = {};
    let name
    {% for object in cl.result_list %}
    name = "{{ object.products}}";
    if(temp.indexOf(name)==-1){
        temp.push(name);
        bg.push(randomColorGenerator())
        dats[name]=1;
    }
    else dats[name]++;
    {% endfor %}
    lineChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: Object.keys(dats),
            datasets: [{
                data: Object.values(dats),
                backgroundColor: bg,
            }]
        },
        options: options
    });
    dats = {};
    temp=[];
    for(let i in hours){
        dats[i]=0;
    }
    ctx = document.getElementById("time-chart");
    {% for object in cl.result_list %}
       dats["{{object.created.hour}}"]++;
    {%endfor%}
    lineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: Object.keys(dats),
            datasets: [{
                data: Object.values(dats),
                borderColor:randomColorGenerator()
            }]
        },
        options: {
            responsive:true,
            legend: {
                display:false,
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            },
            scales:{
                yAxes:[{
                    ticks:{
                        min:0,
                        stepSize:5,
                    },
                }]
            }
        }
    });      
}

</script>
{% endblock extrahead %} 
{% block content %}
<h1>Graphs</h1>
<hr />
<div class="row">
  <div class="col-sm-4">
    <canvas id="gender-chart" style="width: 100 !important;"></canvas>
  </div>
  <div class="col-sm-4">
    <canvas id="model-chart" style="width: 100px !important;"></canvas>
  </div>
</div>
<div class="row">
    <canvas id="time-chart" style="width:500px; height:200px !important"></canvas>
</div>
{{ block.super }} 
{% endblock content%}